name: 'Postman Collection Sync'
description: 'Github Action to update your postman collection'
author: 'Fern'
inputs:
  api-key:
    required: true
    description: 'Postman API Key'
  workspace-id: 
    required: true  
    description: 'Postman Workspace ID for this collection'
  collection-path: 
    required: true
    description: 'Path to the postman collection'
runs:
  using: 'node16'
  main: 'dist/index.js'
